import React from 'react';
import Head from "next/head";
import Link from "next/link";
import PageHeader from './pageHeader';

type PageContent = {children: React.ReactNode, home?:boolean}

export default function Layout({children, home=false}: PageContent) {
    return (
        <div>
            <Head>
                <title>{"TracTruc"}</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <PageHeader></PageHeader>
            <main>
                {children}
            </main>
        </div>
    )
}